#!/usr/bin/env php

<?php

set_time_limit(0);

require  \realpath(__DIR__ . '/..') . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;
$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';
if ($debug) {
    Debug::enable();
}
$kernel = new \Symfony\Bundle\FrameworkBundle\Tests\Functional\app\AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);